GET http://localhost:4000/events


###
GET http://localhost:4000/events/2df4343d-ab9e-4048-8731-73a9da317f29

###
POST http://localhost:4000/events
Content-Type: application/json

{
    "description": "Peça de Teatro Y",
    "type": "TEATRO",
    "date": "2025-11-15T21:00:00",
    "startSales": "2025-03-01T09:00:00",
    "endSales": "2025-11-14T23:59:59",
    "price": 80.50
}

###
POST http://localhost:4000/events
Content-Type: application/json

{
    "description": "Show da banda Y",
    "type": "SHOW",
    "date": "2025-11-15T21:00:00",
    "startSales": "2025-03-01T09:00:00",
    "endSales": "2025-11-14T23:59:59",
    "price": 180.50

}

###
POST http://localhost:4000/events
Content-Type: application/json

{
    "description": "Show da banda X",
    "type": "TEATRO",
    "date": "2025-11-15T21:00:00",
    "startSales": "2025-03-01T09:00:00",
    "endSales": "2025-11-14T23:59:59",
    "price": 150.50
}



###
PUT http://localhost:4000/events/e4d51e53-f568-4b6a-a578-4a94637d036b
Content-Type: application/json

{
    "id": "e4d51e53-f568-4b6a-a578-4a94637d036b",
    "description": "Peça de Teatro Y",
    "type": "TEATRO",
    "date": "2025-11-15T21:00:00",
    "startSales": "2025-03-01T09:00:00",
    "endSales": "2025-11-14T23:59:59",
    "price": 175.0
}

###
DELETE http://localhost:4000/events/delete
Content-Type: application/json

{
    "id": "54997542-e69d-4cef-956b-8a5bbc761e16"
}

###
POST http://localhost:4000/sales
Content-Type: application/json

{
    "userId": "8a6ee1fe-59dd-42bd-8d13-b566ee73b9c6",
    "eventId": "e4d51e53-f568-4b6a-a578-4a94637d036b",
    "saleStatus": "CANCELADO"
}

###
POST http://localhost:4000/sales
Content-Type: application/json

{
    "userId": "8522852b-5d14-41f9-8d39-8a2dfacef86c",
    "eventId": "981d0168-3e2a-4919-a53d-336970efa28c",
    "saleStatus": "PAGO"
}

###
POST http://localhost:4000/sales
Content-Type: application/json

{
    "userId": "12cd6206-c3cf-4c35-a2c3-0987ba0cdd06",
    "eventId": "4643cd64-0a24-4eeb-ab22-cc948c5c406a",
    "saleStatus": "EM_ABERTO"
}

###
GET http://localhost:4000/sales

###
GET http://localhost:4000/sales/cb888280-da8d-4604-9458-56aeae4f72cc

###
GET http://localhost:4000/sales/user/8522852b-5d14-41f9-8d39-8a2dfacef86c

###
PUT http://localhost:4000/sales/status
Content-Type: application/json

{
    "saleId": "f15daa6a-adce-4333-afe0-ddb502689567",
    "newStatus": "PAGO"
}


###
DELETE http://localhost:4000/sales/delete
Content-Type: application/json

{
    "id": "f15daa6a-adce-4333-afe0-ddb502689567"
}
